#spring.application.name=despesas

# ==========================================
# CONFIGURAÇÕES DE BANCO DE DADOS (POSTGRES)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/despesas_db
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ==========================================
# Atualiza o esquema do banco automaticamente baseado nas Entidades
spring.jpa.hibernate.ddl-auto=update

# Exibe no console o SQL que está sendo executado por baixo dos panos
spring.jpa.show-sql=true

# Formata o SQL no console para ficar mais legível
spring.jpa.properties.hibernate.format_sql=true

# Especifica o dialeto do banco de dados
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
